#!/bin/bash

set -e

alias python=/usr/bin/python3
alias pip=/usr/bin/pip3

brew info cairo >/dev/null || brew install cairo
which pipreqs >/dev/null || pip install pipreqs
pipreqs --force
pip install -r requirements.txt

dir=$(
	cd $(dirname "$0")
	pwd
)

mkdir -p ~/Library/LaunchAgents
mkdir -p ~/.local/share/kitty
sudo ln -sf $(which tmux) /usr/local/bin/tmux
ln -sf "${dir}/com.aweis.theme-reactor.plist" ~/Library/LaunchAgents/com.aweis.theme-reactor.plist
launchctl unload ~/Library/LaunchAgents/com.aweis.theme-reactor.plist 2>/dev/null || true
launchctl load -w ~/Library/LaunchAgents/com.aweis.theme-reactor.plist
