#!/bin/zsh

kitty_dir="${0:a:h}"
theme="$kitty_dir/current-theme.conf"

tokyonight_dir="$HOME/.local/share/nvim/lazy/tokyonight.nvim/extras/kitty"
light="$tokyonight_dir/tokyonight_day.conf"
dark="$tokyonight_dir/tokyonight_moon.conf"

# cattpuccin colors
dark="$kitty_dir/themes/mocha.conf"
light="$kitty_dir/themes/latte.conf"

[[ "$(defaults read -g AppleInterfaceStyle 2>/dev/null)" = "Dark" ]] \
  && target="$dark" || target="$light"

rm -rf "$theme"
ln -s "$target" "$theme"

for pid in "$(ps -x | grep '/Applications/kitty.app/Contents/MacOS/kitty' | grep -v grep | awk '{ print $1 }')"; do
    kill -SIGUSR1 $pid
done
