#!/bin/zsh

kitty_dir="${0:a:h}"
theme="$kitty_dir/current-theme.conf"
nvim_lazy_dir=$HOME/.local/share/nvim/lazy

case "$1" in
  "tokyonight")
    dir="$nvim_lazy_dir/tokyonight.nvim/extras/kitty"
    light="$dir/tokyonight_day.conf"
    dark="$dir/tokyonight_moon.conf"
    ;;
  "catppuccin")
    dark="$kitty_dir/themes/mocha.conf"
    light="$kitty_dir/themes/latte.conf"
    ;;
  "onedark")
    dir="$nvim_lazy_dir/onedarkpro.nvim/extras/kitty"
    dark="$dir/onedarkpro_onedark.conf"
    light="$dir/onedarkpro_onelight.conf"
    ;;
  "kanagawa")
    dir="$nvim_lazy_dir/kanagawa.nvim/extras/kitty"
    dark="$dir/kanagawa.conf"
    light="$dir/kanagawa_light.conf"
    ;;
  *)
    dark="$kitty_dir/themes/gruvbox_dark.conf"
    light="$kitty_dir/themes/gruvbox_light.conf"
    ;;
esac

[[ "$(defaults read -g AppleInterfaceStyle 2>/dev/null)" = "Dark" ]] \
  && target="$dark" || target="$light"

rm -rf "$theme"
ln -s "$target" "$theme"

for pid in "$(ps -x | grep '/Applications/kitty.app/Contents/MacOS/kitty' | grep -v grep | awk '{ print $1 }')"; do
    kill -SIGUSR1 $pid
done
