alias ag=rg
alias d=z
alias git="git --no-pager"
alias gos=go-search
alias hf=helmfile
alias int='curl -Ss https://google.com'
alias k=kubectl
alias kb=kubebuilder 
alias kcg='kubectl config get-contexts'
alias kp=kube-prompt
alias kw='watch kubectl'
alias ll="exa -l --git -h"
alias os=operator-sdk
alias python=/usr/local/bin/python3.9
alias rms='rm -rf ~/.local/share/nvim/swap/*'
alias tf=terraform
alias tmux="TERM=screen-256color tmux"
alias tmuxs='vim ~/.tmux.conf'
alias tt=gotestsum
alias vim='nvim'
alias vimns='vimn ~/.config/nvim/init-b.lua' 
alias vims='vim ~/.config/nvim/init.vim'
alias zshs='vim ~/.zshrc'
