# Starship configuration
format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$kubernetes\
$vcsh\
$fossil_branch\
$fossil_metrics\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$quarto\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory\
$aws\
$openstack\
$azure\
$direnv\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$shell\
$character"""

# Kubernetes module configuration
[kubernetes]
format = 'on [⛵ $context \($namespace\)](dimmed green) '
disabled = false
# Always show when kubectl context is available
detect_extensions = []
detect_files = []
detect_folders = []

[[kubernetes.contexts]]
context_pattern = "gke_staging-287520_us-east4_us-east4-tf-gcp-staging-cluster"
context_alias = "staging"

[[kubernetes.contexts]]
context_pattern = "gke_platform-287919_us-east4_us-east4-tf-gcp-platform-cluster"
context_alias = "platform"

[[kubernetes.contexts]]
context_pattern = "gke_production-287919_us-east4_us-east4-tf-gcp-production-cluster"
context_alias = "production"

[[kubernetes.contexts]]
context_pattern = "gke_calbot3-staging_us-east1_calbot3-calbot"
context_alias = "calbot3-staging"

[[kubernetes.contexts]]
context_pattern = "gke_calbot4-staging_us-east1_calbot4-calbot"
context_alias = "calbot4-staging"

[[kubernetes.contexts]]
context_pattern = "gke_calbot5-staging_us-east1_calbot5-calbot"
context_alias = "calbot5-staging"

[[kubernetes.contexts]]
context_pattern = "gke_calbot6-staging_us-east1_calbot6-calbot"
context_alias = "calbot6-staging"

[[kubernetes.contexts]]
context_pattern = "gke_calbot7-production_us-east1_calbot7-calbot"
context_alias = "calbot7-prod"

[[kubernetes.contexts]]
context_pattern = "gke_calbot8-production_us-east1_calbot8-calbot"
context_alias = "calbot8-prod"

[[kubernetes.contexts]]
context_pattern = "gke_mi-recall-production_us-east1_mi-recall-transcription"
context_alias = "recall-prod"

[[kubernetes.contexts]]
context_pattern = "gke_mi-recall-staging_us-east1_mi-recall-apps"
context_alias = "recall-staging"

[[kubernetes.contexts]]
context_pattern = "gke_qzlt-prod-webapp_us-central1_prod"
context_alias = "qzlt-prod"

[[kubernetes.contexts]]
context_pattern = "gke_qzlt-stage-webapp_us-central1_staging"
context_alias = "qzlt-staging"

[[kubernetes.contexts]]
context_pattern = "gke_calendly-edw-production_us-east4_us-east4-data-platform-comp-9c50cb26-gke"
context_alias = "edw-prod"

[[kubernetes.contexts]]
context_pattern = "orbstack"
context_alias = "orbstack"

[[kubernetes.contexts]]
user_pattern = "dev.local.cluster.k8s"
user_alias = "dev"

[[kubernetes.contexts]]
user_pattern = "root/.*"
user_alias = "root"

# Character configuration
[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

# Directory configuration
[directory]
truncation_length = 3
truncate_to_repo = false

